server:
  port: 9002
spring:
  application:
    name: contact-service
eureka:
  instance:
    hostname: localhost


  
#eureka:
  # instance:
#    hostname: localhost
#  client:
#    service-url:
#     defaultZone: http://localhost:8761/eureka